FROM node:22-alpine

WORKDIR /app

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli

# Copiar package.json e package-lock.json
COPY package*.json ./

# Instalar dependências
RUN npm ci

# Copiar o .env para o build (se existir)
COPY .env* ./

# Expor porta
EXPOSE 4200

# Comando padrão (desenvolvimento com hot reload)
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
